confirm-before-quit = false
hide-cursor-when-typing = true
# ignore-selection-foreground-color = false

theme = "darkMeRio-Slim"

# Padding-x
padding-x = 20
padding-y = [0, 10]

# Line height
line-height = 1.4

# Startup directory
working-dir = "/Users/rapha/Documents/__"

[cursor]
    shape = 'Beam'
    blinking = false
    blinking-interval = 800

[editor]
    program = "nvim"
# args = []

[window]
    blur = false
    opacity = 1.0
    mode = "Fullscreen"
    decorations = "Disabled"

[renderer]
    level = 1
    target-fps = 165
    backend = "Vulkan"
    performance = "high"
    disable-unfocused-render = false
# filters = []

[fonts]
    size = 18

[scroll]
    multiplier = 3.0
    divider = 1.0

[navigation]
    mode = "BottomTab"
    clickable = false
    hide-if-single = true
    use-current-path = false
# color-automation = []

[platform]
windows.shell.program = "pwsh"
windows.shell.args = ["-l", "-NoLogo"]
